### ISSUE TITLE
Mac OS - Error When trying to open command file

### ISSUE THREAD

**Issue by codrinMitu** [just-harry/tiny-ui-fix-for-ts3#2]
When I open the command file I get this error:
<img width="1440" alt="Screenshot 2023-12-28 at 16 21 03" src="https://github.com/just-harry/tiny-ui-fix-for-ts3/assets/87667992/d1285c9c-64a4-401d-a340-ca6f0dab3b13">

**Comment by codrinMitu** [comment]
I also tried opening it via terminal using the open command and sudo but I still got the error.

**Comment by just-harry** [comment]
You may need to set the executable bit/permission for the script. \
Try `chmod +x tiny-ui-fix-for-ts3.command` in the terminal (replace `tiny-ui-fix-for-ts3.command` with the path of the file, if the path is different)

---

May I ask which version of macOS you are using, please? \
I may need to change how the script is packaged for newer versions of macOS, to avoid this error in future

**Comment by codrinMitu** [comment]
Thanks for the fix, it worked great! I'm using macOS Sonoma 14.2.

**Comment by just-harry** [comment]
Wonderful, thank you for telling for me which version of macOS you're using. \
Turns out that this is a change that was [introduced with macOS Catalina](https://forum.xojo.com/t/catalina-unzip-file-permissions-problems/52435) (which is the version I stopped one short of when testing :/), so I'll fix that for later releases
